### ISSUE TITLE
Ninja Gaiden Enigma 

### ISSUE THREAD

**Issue by Renshi01** [skyline-emu/skyline-games-list#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1318

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/search?client=lightning&ie=UTF-8&oe=UTF-8&q=poco+x3+pro

### Game Behaviour

![Screenshot_2022-08-23-15-31-48-988_com mxtech videoplayer pro](https://user-images.githubusercontent.com/105548456/186104493-ab77b0ad-b6b6-4746-a62b-bd3f2d7ed8f6.jpg)

https://youtu.be/oRdD2JDNIQ8

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[logs.zip](https://github.com/skyline-emu/skyline-games-list/files/9400355/logs.zip)

**Comment by Crytonics** [comment]
@Renshi01 you are banned from the repository because your log contains a name of a piracy website.
