### ISSUE TITLE
Xel

### ISSUE THREAD

**Issue by Ellian** [skyline-emu/skyline-games-list#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1320

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_tab_s6-9781.php

### Game Behaviour

- 0 fps
- black screen, not loading 

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by ImaDoor2785** [comment]
piracy in logs 
gonna get banned

**Comment by guranu** [comment]
@Crytonics close this issue.

**Comment by Ellian** [comment]
New log file
[logs.zip](https://github.com/skyline-emu/skyline-games-list/files/9430246/logs.zip)

**Comment by Crytonics** [comment]
@Ellian you are banned from the repository because your log contains a name of a piracy website.
