### ISSUE TITLE
Kill La Kill THE GAME IF

### ISSUE THREAD

**Issue by qiangyuqq** [skyline-emu/skyline-games-list#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1338

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_10_5g-10082.php

### Game Behaviour

There are 4 screens in this game
![Screenshot_2022-08-27-22-15-21-259_skyline emu](https://user-images.githubusercontent.com/112594068/187811018-c4b4b8b4-7c68-492f-ac4a-cc10ae00ecd5.jpg)
![Screenshot_2022-09-01-08-32-17-301_com antutu benchmark full](https://user-images.githubusercontent.com/112594068/187811024-78185787-44df-4c73-900e-fcbb476b7d1b.jpg)
![Screenshot_2022-09-01-08-31-58-915_com antutu benchmark full](https://user-images.githubusercontent.com/112594068/187811026-636c4d55-9109-4b67-abbb-6c60a47e96f1.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation(errors).txt](https://github.com/skyline-emu/skyline-games-list/files/9466024/emulation.errors.txt)
[emulation(information).txt](https://github.com/skyline-emu/skyline-games-list/files/9466025/emulation.information.txt)

**Comment by K11MCH1** [comment]
an issue already exists here https://github.com/skyline-emu/skyline-games-list/issues/576

Please add your feedback in the comments there and next time use the search tool to prevent posting duplicate issues.

**Comment by qiangyuqq** [comment]
> an issue already exists here #576
> 
> Please add your feedback in the comments there and next time use the search tool to prevent posting duplicate issues.

It's not the same issue

**Comment by K11MCH1** [comment]
> > an issue already exists here #576
> > Please add your feedback in the comments there and next time use the search tool to prevent posting duplicate issues.
> 
> It's not the same issue

"Issue" as in "post".
1 post per game. Feedback is posted in the comments. I know, not very clear at first sight, but thats the way it is.
