### ISSUE TITLE
GPU MALLI ESTÁ SENDO ESQUECIDA 

### ISSUE THREAD

**Issue by davyson123** [skyline-emu/skyline-games-list#104]
Oi boa noite aos dev. Amados tem como vcs se dedicarem mais também na gpu malli ?. Pq está sendo esquecida essa gpu. Por favor. Obg

**Comment by koukichi7010** [comment]
This Repo is for Skyline Games list

**Comment by HalogenGam3r** [comment]
BR: Este repositório é apenas para a lista de jogos. Ir para https://github.com/skyline-emu/skyline para seus problemas. Além disso, você deve falar Inglês para a questão.

ENG: This repository is only for the game list. Go to https://github.com/skyline-emu/skyline for your issues. Also you should speak English for the issue.
