### ISSUE TITLE
Nintendo Switch Sports

### ISSUE THREAD

**Issue by Thepowa753** [skyline-emu/skyline-games-list#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1338

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_12_pro-11287.php

### Game Behaviour

- Deadlock
- Not booting

https://user-images.githubusercontent.com/44495483/188262968-d6858af2-ac5c-442a-b77e-96cf2cafc827.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/9482238/emulation.sklog.txt)

**Comment by dimaxdqwerty** [comment]
Copy of https://github.com/skyline-emu/skyline-games-list/issues/600
