### ISSUE TITLE
Ben 10

### ISSUE THREAD

**Issue by Dynamic58** [skyline-emu/skyline-games-list#1074]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Tested Build

#1341

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/oneplus_8_pro-9919.php

### Game Behaviour

-Some surrounding objects may flicker
-Sometimes the characters have missing textures
-UI is not visible (Start, Continue, Quit etc.)
-HUD/GUI not visible (Health, Dialogues, Alien picking wheel, etc.)
-Sometimes freezes on startup
-Sound/music is proper 
-Cutscene voicelines are proper 
-Game is playable (30-60 fps) 
![Screenshot_2022-09-05-00-00-34-34_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/105129577/188328579-13eee46d-e2d1-4c2e-bd2c-0825fa85def8.jpg)
![Screenshot_2022-09-04-23-59-59-71_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/105129577/188328583-b5a83f42-a8b1-4cdb-8b84-16937571796a.jpg)
![Screenshot_2022-09-04-23-58-55-03_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/105129577/188328590-9446df24-1205-454e-a66f-099898ad065f.jpg)
![Screenshot_2022-09-04-23-59-05-00_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/105129577/188328593-eddb1038-b5f0-4a90-80d6-fbb3db70c8e4.jpg)
 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9485298/emulation.zip)

**Comment by EZonTheEyes** [comment]
Duplicate issue- please add comment updating the preexisting issue (#960)
