### ISSUE TITLE
White Day: A Labyrinth Named School

### ISSUE THREAD

**Issue by ericsonia** [skyline-emu/skyline-games-list#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1342

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/asus_zenfone_5z_zs620kl-9096.php

### Game Behaviour

- In game
- Docked mode
- Major graphical issues
- Audio stuttering in some part
- I'm using driver turnip skyline fixes v1
![Screenshot_20220910-214118748](https://user-images.githubusercontent.com/55049420/189488769-539f18b5-2159-445b-b0d7-a819c344741e.jpg)
![Screenshot_20220910-214151891](https://user-images.githubusercontent.com/55049420/189488778-b1fba7d3-9825-4052-9b3b-8be7fb40f6d7.jpg)
![Screenshot_20220910-214205314](https://user-images.githubusercontent.com/55049420/189488787-93809cf8-163a-4afa-8120-c4dd8a4dcc9e.jpg)
![Screenshot_20220910-204846339](https://user-images.githubusercontent.com/55049420/189488792-9bc01a6d-55e6-4863-88d9-9f1d4f7d84d4.jpg)
![Screenshot_20220910-214426538](https://user-images.githubusercontent.com/55049420/189488810-a564d45f-95f3-4a47-b175-2ca507a3b1d1.jpg)
![Screenshot_20220910-214306738](https://user-images.githubusercontent.com/55049420/189488814-fab8d3f4-0a6b-41ce-8bba-f7677b6cddef.jpg)
![Screenshot_20220910-214444418](https://user-images.githubusercontent.com/55049420/189488834-feea1f1c-3515-43f6-9e71-683734674531.jpg)
![Screenshot_20220910-214256091](https://user-images.githubusercontent.com/55049420/189488841-58e5d690-31e7-4a7c-8b3d-a839dbcd42ca.jpg)
![Screenshot_20220910-214459841](https://user-images.githubusercontent.com/55049420/189488843-1111ca01-a2df-4941-9181-73fbe45b528b.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[White Day: A Labyrinth Named School.zip](https://github.com/skyline-emu/skyline-games-list/files/9540647/White.Day.A.Labyrinth.Named.School.zip)

**Comment by Dekuzearou** [comment]
@Sovietfowl piracy website in log

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a piracy website name.

**Comment by raiyuulmao** [comment]
Errr errr skyline simulador pierrtos de Caribbean
