### ISSUE TITLE
yomawari the long night collection

### ISSUE THREAD

**Issue by imxade** [skyline-emu/skyline-games-list#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1351

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_pocophone_f1-9293.php

### Game Behaviour

- shows nothing
- 0 fps

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by K11MCH1** [comment]
@imxade Change the log extension to .txt and upload please.

**Comment by imxade** [comment]
> @imxade Change the log extension to .txt and upload please.

done

**Comment by Crytonics** [comment]
@imxade You are banned from the repository because your log contains a name of a piracy website.
