### ISSUE TITLE
Donut county

### ISSUE THREAD

**Issue by Michae12098** [skyline-emu/skyline-games-list#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

 Tested Build 

1345

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/Redmi10C

### Game Behaviour

Игра работает, но всего-лишь 15Fps графических багов не замечено. 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Info

**Comment by Crytonics** [comment]
Upload log, and type in English.

**Comment by Michae12098** [comment]
Ok

пн, 26 сент. 2022 г., 02:44 Crytonics ***@***.***>:

**Comment by Crytonics** [comment]
User didn't update issue.
