### ISSUE TITLE
The untitled goose game 

### ISSUE THREAD

**Issue by Puneet124421** [skyline-emu/skyline-games-list#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1359

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/motorola_moto_g51_5g-11194.php

### Game Behaviour

Whenever I open untitled goose game the fps shows only 11 to 13 and after a few mins whenever a moving NPC character arrives the screen suddenly turns blue and the game freezes and after a few seconds the game crashes

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

``https://drive.google.com/file/d/13wYlB90nh4xGoftlV5IVUah7p0vDpSsr/view?usp=drivesdk

**Comment by MuhSlam** [comment]
This game are already on list #115
Don't make duplicate , use search tool before posting
@Crytonics close this ..

**Comment by TheASVigilante** [comment]
@Puneet124421 
Also your log is broken only you have access to it it seems
