### ISSUE TITLE
Super Mario Odyssey

### ISSUE THREAD

**Issue by Leentek006** [skyline-emu/skyline-games-list#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-{Version 3}

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_black_shark_3-10110.php

### Game Behaviour

Missing texture or shadow glitch gone when you jump off a cliff and reloads the stage 

[super mario odyssey](https://youtu.be/E-pZS7-_hZ4)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[youtube test](https://youtu.be/E-pZS7-_hZ4)

**Comment by K11MCH1** [comment]
An issue already exists here https://github.com/skyline-emu/skyline-games-list/issues/1
Please check if an issue exists before posting. Only 1 issue per game allowed.
