### ISSUE TITLE
Teenage Mutant Ninja Turtles: Shredder's Revenge

### ISSUE THREAD

**Issue by W5kjj** [skyline-emu/skyline-games-list#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

12

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_nova_7i-10058.php

### Game Behaviour

![Screenshot_20221031_141106_skyline emu](https://user-images.githubusercontent.com/113975887/198995003-5e894586-777e-433f-aae0-79117d63f0c1.jpg)

![Screenshot_20221031_141039_skyline emu](https://user-images.githubusercontent.com/113975887/198994994-ccbb995e-51d8-40cd-9126-10ce1755a131.jpg)
The game boot it crash when you choose character 
![Screenshot_20221031_141032_skyline emu](https://user-images.githubusercontent.com/113975887/198994980-2de95f97-38c3-4073-bde7-3b027f7e9918.jpg)
Device:huawei Nova 7i

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Ye

**Comment by K11MCH1** [comment]
An issue already exists for this game.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

Please use the search tool next time. https://github.com/skyline-emu/skyline-games-list/issues/674
