### ISSUE TITLE
Pokemon Sword

### ISSUE THREAD

**Issue by ChrisM20** [skyline-emu/skyline-games-list#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_mate_20-9367.php

### Game Behaviour

Pokemon sword, all issues I found.

![Screenshot_20221031_073854_skyline emu](https://user-images.githubusercontent.com/60308449/199028076-e0f46541-758c-4d78-b91b-15585a75c9fe.jpg)
![Screenshot_20221031_073946_skyline emu](https://user-images.githubusercontent.com/60308449/199028473-5008183c-a1a1-4a58-ae8f-fe709cd35fa9.jpg)
![Screenshot_20221031_074108_skyline emu](https://user-images.githubusercontent.com/60308449/199028522-cc390939-bdab-4f1d-8650-f065317f534e.jpg)
I see that some cinematics and some parts are blurred, in pokemon camp when using a toy you can see a little more, I also see that some graphics are missing like the reactions in Pokémon camp

![Screenshot_20221031_073912_skyline emu](https://user-images.githubusercontent.com/60308449/199028957-a01c26fe-8764-4d36-8693-310f3d5a10ee.jpg)
In some places it looks normal and others look darker like in caves, apart from the fact that I notice that it is always night

![Screenshot_20221031_080229_skyline emu](https://user-images.githubusercontent.com/60308449/199029761-55360263-4f04-48d0-a13a-fb6f5e8bd6f2.jpg)
It happened to me when leaving and re-entering an area

![Screenshot_20221031_074931_skyline emu](https://user-images.githubusercontent.com/60308449/199029957-8878c3a3-7c1b-4fa6-b125-78f64bf4a842.jpg)
![Screenshot_20221031_075030_skyline emu](https://user-images.githubusercontent.com/60308449/199030019-76800bf4-04e4-4d69-a0ca-03dd3d8c3cd0.jpg)
Also notice that I change most of the words in the game, similar to the audio in the game, which is normal for a moment but turns weird

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/9901808/emulation.sklog.zip)

**Comment by K11MCH1** [comment]
An issue already exists for this game.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

Please use the search tool next time.

**Comment by ChrisM20** [comment]
👎 Something doesn't add up to me, it was announced on May 4, and the game has been working for a very short time, why more consideration in a longer report? I guess it was edited, and if one reports with more description why ignore it?  Can't help fix the errors?  , no need to close it just because it was duplicated from an out of time edited comment.  There's also no need to tell me to look first when there's nothing to warn you of it just like the duplicate.  Better error handling is needed.

**Comment by K11MCH1** [comment]
> 👎 Something doesn't add up to me, it was announced on May 4, and the game has been working for a very short time, why more consideration in a longer report? I guess it was edited, and if one reports with more description why ignore it? Can't help fix the errors? , no need to close it just because it was duplicated from an out of time edited comment. There's also no need to tell me to look first when there's nothing to warn you of it just like the duplicate. Better error handling is needed.

Sorry for the inconvenience.
We do need a better reporting system and glad you mention it. I am currently working on one in which people won't have to leave the Discord app to post an update.

I will use this post to update the existing issue so your efforts wouldn't have been in vain.
Hope this clears it.
