### ISSUE TITLE
Salt And Sanctuary

### ISSUE THREAD

**Issue by TheMercenary333** [skyline-emu/skyline-games-list#1162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://www.gsmarena.com/huawei_p_smart_2019-9409.php

### Game Behaviour

- In-game both handheld and dock mode
- The game has low fps 
- Audio is puffering 
- Character and enemy graphics are missing
![Screenshot_20221101_000547_skyline emu](https://user-images.githubusercontent.com/74915480/199113774-765e86c3-9ff8-4747-99ae-6f5a59809b44.jpg)
- The game crashed sometimes after trying to take a screenshot 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Salt And Sanctuary.txt](https://github.com/skyline-emu/skyline-games-list/files/9905179/Salt.And.Sanctuary.txt)

**Comment by K11MCH1** [comment]
An issue already exists for this game.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

Kindly use the search tool next time.
