### ISSUE TITLE
Darkwood

### ISSUE THREAD

**Issue by TheMercenary333** [skyline-emu/skyline-games-list#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://www.gsmarena.com/huawei_p_smart_2019-9409.php

### Game Behaviour

- The game menu is booting 
- The game goes deadlock after starting a new game on the loading screen
- New game settings UI is not visible

https://user-images.githubusercontent.com/74915480/199116015-9d483a3b-208a-471a-baf4-ab01d59a1919.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[darkwood_docked.txt](https://github.com/skyline-emu/skyline-games-list/files/9905201/darkwood_docked.txt)
[darkwood_handheld.txt](https://github.com/skyline-emu/skyline-games-list/files/9905205/darkwood_handheld.txt)

**Comment by K11MCH1** [comment]
An issue already exists for this game.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

I will copy the contents and update the existing issue.
Kindly use the search tool next time.
