### ISSUE TITLE
Webbed

### ISSUE THREAD

**Issue by TheMercenary333** [skyline-emu/skyline-games-list#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-6

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://www.gsmarena.com/huawei_p_smart_2019-9409.php

### Game Behaviour

- Game doesn't launch 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Webbed_d.txt](https://github.com/skyline-emu/skyline-games-list/files/9905258/Webbed_d.txt)

**Comment by K11MCH1** [comment]
An issue already exists for this game.
Only 1 issue per game allowed. If an issue already exists for a game and you need to report an update you need to post it in the comment section.

I will copy the contents and update the existing issue.
Kindly use the search tool next time.
