### ISSUE TITLE
Ghost song

### ISSUE THREAD

**Issue by Tyronepogi** [skyline-emu/skyline-games-list#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1453

### Android Version

12

### SoC type

Other

### Device GSMArena link

https://www.gsmarena.com:/<huawei>

### Game Behaviour

Black screen
![Screenshot_20221106_232854_skyline emu](https://user-images.githubusercontent.com/117536767/200179640-b32edefe-7e6c-4fee-8e9e-d0a4ead0a24b.jpg)
Ghost song crashed 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

None

**Comment by K11MCH1** [comment]
There is already an existing issue here https://github.com/skyline-emu/skyline-games-list/issues/1179
Please use the search function next time.
