### ISSUE TITLE
Snow Bros Special

### ISSUE THREAD

**Issue by Jan0722** [skyline-emu/skyline-games-list#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-8

### Android Version

10

### SoC type

Exynos

### Device GSMArena link

Samsung A30

### Game Behaviour

![Screenshot_20221106-112901](https://user-images.githubusercontent.com/105393454/200182822-d19bd79f-e12c-4176-a37f-5c09fda16f1e.jpg)
the game works the performance is decent but when it reaches the loading screen it closes unexpectedly.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

**Comment by K11MCH1** [comment]
Can you please post a log. Change the extension to .txt and post it.

**Comment by K11MCH1** [comment]
Nevermind. Closed for duplicate issue. Please use the search function next time to avoid duplicate issues. 1 issue per game.
