### ISSUE TITLE
Factorio

### ISSUE THREAD

**Issue by x1unix** [skyline-emu/skyline-games-list#1185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

v0.0.3

### Android Version

13

### SoC type

Other

### Device GSMArena link

https://www.gsmarena.com/google_pixel_6-11037.php

### Game Behaviour

I tested two versions of the game (initial 1.1.68 and latest update 1.1.69).

* 1.1.68 version starts but stuck on splash screen (shows factorio splash screen, plays startup sound but without progress bar)
* Latest version shows blank black screen

![image](https://user-images.githubusercontent.com/9203548/200698617-7a2da74e-e7c6-40f6-9e0d-422d064ba21a.png)

**Screenshot of 1.1.68 version**

**Supplementary info**

* OS: Android 13
* SoC: Google Tensor
* [logs](https://github.com/skyline-emu/skyline-games-list/files/9965964/logs.zip).
* [Video](https://user-images.githubusercontent.com/9203548/200698980-45b011bb-4038-452f-af57-c6e8f11247eb.mp4)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[logs.zip](https://github.com/skyline-emu/skyline-games-list/files/9965983/logs.zip)

**Comment by Catif** [comment]
### Device GSMArena link
https://www.gsmarena.com/xiaomi_pad_5-11042.php

### Game Behaviour
Same issue of the video and the picture. (v1.1.68)

### Supplementary info
- OS: Android 11

### Log file
[log.zip](https://github.com/skyline-emu/skyline-games-list/files/9995721/log.zip)

**Comment by x1unix** [comment]
FYI Factorio has a native arm build for macOS M1, maybe this will help in debugging
