### ISSUE TITLE
<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by Sksjsjkauddh** [skyline-emu/skyline-games-list#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Gkctufcuf

### Android Version

11

### SoC type

Mediatek

### Device GSMArena link

BhvjyvdivyFivzruvxrbyx😭

### Game Behaviour

Mario 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Mario hh ycyyknvuzrlvkDHuvdcuetvzuet zdu hd,dh j,d d,

**Comment by TheASVigilante** [comment]
Delet this
