### ISSUE TITLE
Tararia

### ISSUE THREAD

**Issue by abc1356** [skyline-emu/skyline-games-list#1207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1522

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/vivo_y31s-10660.php

### Game Behaviour

Freeze when loading map，audio works fine
![Screenshot_20221122_160419](https://user-images.githubusercontent.com/76833645/203260318-8777d62f-8d21-42ab-9e70-3e0d860d4ff9.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/10065216/emulation.txt)

**Comment by EZonTheEyes** [comment]
Repost of Existing issue, if you have new information update in a comment.
https://github.com/skyline-emu/skyline-games-list/issues/10
