### ISSUE TITLE
Cooking simulator

### ISSUE THREAD

**Issue by Usserrnnaammee** [skyline-emu/skyline-games-list#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-11

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f3-10758.php

### Game Behaviour

Broken graphics
![Screenshot_2022-11-25-18-20-53-794_skyline emu](https://user-images.githubusercontent.com/118924817/204017976-09c68296-8d8f-41c8-bc9b-0a82f2854dff.jpg)
![Screenshot_2022-11-25-18-21-04-322_skyline emu](https://user-images.githubusercontent.com/118924817/204017986-80d6a59f-f2b9-437c-83d7-9e26ee22fccf.jpg)
Executors 8
Driver turnip v24
Texture hack enable d

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Log:
[emulation.zip](https://drive.google.com/file/d/123kcPBSEuahwsQ5ktz5XolfJil4hRitO/view?usp=drivesdk)

**Comment by EZonTheEyes** [comment]
Repost of existing issue, please add your update to the existing one.
https://github.com/skyline-emu/skyline-games-list/issues/383
