### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AndyRodick1** [skyline-emu/skyline-games-list#1315]
Blurry and Textures crashing #248 
![Screenshot_20221218_140413](https://user-images.githubusercontent.com/103725696/208288800-58fb03ac-16bb-426c-97cd-54066afe75e5.jpg)

**Comment by Mononono87** [comment]
Uhhh I think we need more information.also you did not format it correctly.i also notice you are using skyline edge so I hope you are paying for it.

**Comment by K11MCH1** [comment]
What he said above. Next time fill in the form please.
