### ISSUE TITLE
Owlboy

### ISSUE THREAD

**Issue by K11MCH1** [skyline-emu/skyline-games-list#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1064

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/realme_gt_neo2-11074.php

### Game Behaviour

- Deadlocks after logo.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Owlboy.zip](https://github.com/skyline-emu/skyline-games-list/files/8598032/Owlboy.zip)

**Comment by bylaws** [comment]
Retest please on latest
