### ISSUE TITLE
Scourgebringer

### ISSUE THREAD

**Issue by K11MCH1** [skyline-emu/skyline-games-list#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1064

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/realme_gt_neo2-11074.php

### Game Behaviour

- Playable at full fps.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Scourgebringer.zip](https://github.com/skyline-emu/skyline-games-list/files/8598061/Scourgebringer.zip)

**Comment by EZonTheEyes** [comment]
moved to #187
