### ISSUE TITLE
<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by kamubanya** [skyline-emu/skyline-games-list#1373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-3

### Android Version

11

### SoC type

Mediatek

### Device GSMArena link

Oppo A16

### Game Behaviour

Katana zero

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Katana zero

**Comment by K11MCH1** [comment]
Katana zero is already an existing issue. [Here](https://github.com/skyline-emu/skyline-games-list/issues/3)
Please use the search tool before submitting an issue.

**Comment by Ronny29en** [comment]
K

**Comment by Ronny29en** [comment]
#652

**Comment by martinaguil** [comment]
Mola
