### ISSUE TITLE
Super Dragon Ball heroes World Mission 

### ISSUE THREAD

**Issue by Cristianjjc** [skyline-emu/skyline-games-list#1404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1851

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

m.gsmarena.com/xiaomi_redmi_note_10-ampp-10247.php?espv=1

### Game Behaviour

![Screenshot_2023-02-08-19-41-42-831_skyline emu](https://user-images.githubusercontent.com/124849226/217697363-71582435-9cf0-4920-a779-2860a819018d.jpg)
![Screenshot_2023-02-08-19-42-06-147_skyline emu](https://user-images.githubusercontent.com/124849226/217697369-1a566918-2fac-4c67-b256-69189c0b7349.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file
I146EmuMainApplyDriverPatches: Applied BCeNabler patch
I146EmuMainApplyDriverPatches: Applied GPU memory import patch
I146EmuMainCreateDevice: Vulkan Device:
Name: Adreno (TM) 612
Type: IntegratedGpu
Driver ID: QualcommProprietary
Vulkan Version: 1.1.128
Driver Version: 0.502.0
Queues:
* 3xGC--P: TSB48 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_KHR_shared_presentable_image (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_KHR_external_memory (v0.0.1)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_QCOM_render_pass_store_ops (v0.0.2)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_QCOM_render_pass_shader_resolve (v0.0.4)
* VK_KHR_maintenance1 (v0.0.1)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_KHR_sampler_ycbcr_conversion (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_push_descriptor (v0.0.1)
* VK_EXT_device_memory_report (v0.0.1)
* VK_KHR_device_group (v0.0.2)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_EXT_pipeline_creation_cache_control (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_EXT_global_priority (v0.0.2)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_EXT_line_rasterization (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_dedicated_allocation (v0.0.1)
* VK_KHR_swapchain (v0.0.70)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: false
* Supports Custom Border Color (Without Format): false
* Supports Anisotropic Filtering: true
* Supports Last Provoking Vertex: false
* Supports Logical Operations: false
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
* Supports Push Descriptors: false
* Supports Imageless Framebuffers: false
* Supports Global Priority: true
* Supports Multiple Viewports: false
* Supports Shader Viewport Index: false
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: false
* Supports 16-bit FP: true
* Supports 8-bit Integers: true
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: false
* Supports Patch List Primitive Topology Restart: false
* Supports Transform Feedback: false
* Supports Geometry Shaders: true
*  Supports Vertex Pipeline Stores and Atomics: true
* Supports Fragment Stores and Atomics: true
* Supports Shader Storage Image Write Without Format: true
*Supports Subgroup Vote: true
* Subgroup Size: 64
* BCn Support: 1111111
Quirks:
* Needs Individual Texture Binding Writes: true
* VkImage Mutable Format is costly: true
* Adreno Relaxed Format Aliasing: true
* Adreno Broken Format Reporting: true
* Broken Descriptor Aliasing: true
* Relaxed Render Pass Compatibility: true
* Max Subpass Count: 64
* Max Global Queue Priority: High
I1329EmuMainPipelineManager: Loaded 330 graphics pipelines in 398ms
I1331EmuMainNPDM Metadata:
Title: ID: 100CAF00C462000, Version: 0
Main Thread: Priority: 44, Stack Size: 0x100000
Scheduler: Ideal Core: 0, Core Mask: 0111, Priority: 28 - 59
Kernel Version: v9.1
I1331EmuMainSerialisePipelineCache: Wrote Vulkan pipeline cache to /storage/emulated/0/Android/data/skyline.emu/files/vk_graphics_pipeline_cache/0100CAF00C462000/435100000002010600601F80B070FA05435100000000000201060000 (size: 0x38D75 bytes)
I1342EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I1790EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800006000)
I2000EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x828A18000 (.text @ 0x828A19000)
I2000EmuMainStarting "SUPER DRAGON BALL HEROES WORLD MISSION" (0100CAF00C462000) v1.0.0 by "BANDAI NAMCO Entertainment Inc."
I2002EmuMainExecute: Starting main HOS thread

**Comment by Crytonics** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Tested Build
> 
> 1851
> ### Android Version
> 
> 12
> ### SoC type
> 
> Snapdragon
> ### Device GSMArena link
> 
> m.gsmarena.com/xiaomi_redmi_note_10-ampp-10247.php?espv=1
> ### Game Behaviour
> 
> ![Screenshot_2023-02-08-19-41-42-831_skyline emu](https://user-images.githubusercontent.com/124849226/217697363-71582435-9cf0-4920-a779-2860a819018d.jpg) ![Screenshot_2023-02-08-19-42-06-147_skyline emu](https://user-images.githubusercontent.com/124849226/217697369-1a566918-2fac-4c67-b256-69189c0b7349.jpg)
> ### Is Log Level is set to 'Info'?
> 
>     * [x]  Yes
> 
> 
> ### Log file
> 
> ![Screenshot_2023-02-08-19-42-06-147_skyline emu](https://user-images.githubusercontent.com/124849226/217697515-8c3e05a2-481f-4436-9302-1cc0e8b2e348.jpg)

@Cristianjjc Can you upload log?

**Comment by Cristianjjc** [comment]
@Crytonics I already uploaded the record

**Comment by saidd71** [comment]
Sai

**Comment by saidd71** [comment]
saidduque642@gmail.com

**Comment by saidd71** [comment]
Wizl

**Comment by saidd71** [comment]
Sidi
