### ISSUE TITLE
SpongeBob: Krusty Cook-off

### ISSUE THREAD

**Issue by DeltaVRG** [skyline-emu/skyline-games-list#1447]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Tested Build

Skyline 1909

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link
https://m.gsmarena.com/honor_50-10962.php

Honor 50

### Game Behaviour

Game is playable
Игра воспроизводима

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

SpongeBob: Krusty Cook-Off

**Comment by DeltaVRG** [comment]
No, after first start game crashed

**Comment by EZonTheEyes** [comment]
issue needs log

**Comment by Crytonics** [comment]
Can you upload photo or video of game running?
