### ISSUE TITLE
SUPER MARIO ODYSSEY

### ISSUE THREAD

**Issue by bmcpcmb** [skyline-emu/skyline-games-list#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-0.0.3

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/tcl_10_5g_uw-ampp-10559.php

### Game Behaviour

Here's a little too detailed report on my experience with Skyline. 

My device is a TCL 10 5G UW. It has a SD765G with Adreno 620 and 6GB of RAM. The game barely runs (but it does). Depending on the area (I've tested only the Sand Kingdom) the game can hit from 15FPS to some pretty impressive 45-50FPS. Now then, the game crashes for some reason. Same thing with other titles like Sonic Mania (and that Chemical Plant boss glitch that won't let me finish Act 2) which, after a while, crash or freeze (most commonly crash). I seriously need to know, is this a fault of the emulator or is my device just unluckily cursed and will force the emulator to crash or something? I've seen others test games with the same setup (although a different phone) and I have not heard anything about constant crashes that won't let a man finish their games.

For example, I played from the entrance of the Sand Kingdom all the way to the boss fight in Showdown at the Inverted Pyramid. Everything went smoothly, with a low but steady and somewhat playable frame rate. After the fight and the triple moon collection cutscene, when Mario and Cappy fly off, the emulator just crashes, and won't even save my progress up to that point, forcing me to loop all the way back and have to play it all again.

Anyway, pretty long it is, sure. So to resume. Should I bash my phone with a hammer, or this happens to someone else??? A simple answer is all I need. Nobody will say anything about it. I just need to know if it's the emulator or my device. I need a certain answer from someone who has experienced the same, not just vain conjectures like "eh it's in development so it's probably that". I need something concrete enough to help me rest assured. I'm not even mad at the crashes. Just confused and worried that my phone will never be able to run Switch games without crashing.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Log from Feb. 16 2023](https://drive.google.com/file/d/1t5xKSEYj2knVgWAFkRVngVoT4_Ppz5fH/view?usp=drivesdk) 

Sorry I can't post the log the way I should. I could just upload it somewhere for you to download it.

**Comment by raphaelko62** [comment]
copy of #1 you should close and if you want to report something new go comment there

**Comment by EZonTheEyes** [comment]
see #1
