### ISSUE TITLE
Z<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by Ronny29en** [skyline-emu/skyline-games-list#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

N

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

J

### Game Behaviour

J

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

IkK

**Comment by EZonTheEyes** [comment]
spam
