### ISSUE TITLE
Sonic Dimensions

### ISSUE THREAD

**Issue by DeltaVRG** [skyline-emu/skyline-games-list#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Skyline 1955

### Android Version

12

### SoC type

Snapdragon

https://m.gsmarena.com/honor_50-10962.php

Honor 50

### Game Behaviour

Game is playable
Игра воспроизводима

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Sonic Dimensions port switch

**Comment by EZonTheEyes** [comment]
Log File Needed, device GSMArena link needed

**Comment by mohammad6343** [comment]
Good

**Comment by Crytonics** [comment]
Can you upload photo or video of game running?
