### ISSUE TITLE
Minecraft: Nintendo Switch edition

### ISSUE THREAD

**Issue by bcash06** [skyline-emu/skyline-games-list#1473]
The game works almost flawlessly apart from being able to see through the ground.

Skyline version: 0.3
Minecraft version: 1.0 XCI
Device: S22, xclipse 920 GPU
Android 13

Pic of what i mean
![Screenshot_20230305_140413](https://user-images.githubusercontent.com/33558119/222965322-b4e785c1-4a04-4e37-8167-003d6d2cee34.jpg)

**Comment by EZonTheEyes** [comment]
Submission needs Log file. Also, All versions of skyline with playable commercial games have been released under V0.0.3, we go by Build # for reporting testing. Please adjust the submission with the build # used. Aditionally, please follow proper formatting for submissions.
