### ISSUE TITLE
<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by DroidOFC** [skyline-emu/skyline-games-list#1481]
### Is there an existing fix for this?

- [X] I have searched the existing issues

### Tested Build

Edge-44

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s20_fe_5g-10377.php

### Game Behaviour

*game crash when Im on character choosing

https://user-images.githubusercontent.com/127598934/224481294-64e9e31b-dc4c-455e-89f8-bebef27ecf95.mp4*

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

error

**Comment by EZonTheEyes** [comment]
Already an existing issue (+incorrect formatting), see #1196 #1360 and #247
