### ISSUE TITLE
Cat Quest II

### ISSUE THREAD

**Issue by Wumbee01** [skyline-emu/skyline-games-list#1483]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Tested Build

2089

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_11t

### Game Behaviour

Terrain may flicker, this can be fixed by opening menu, settings and then scrolling through the options, then closing the memu

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/10951058/emulation.txt)

**Comment by EZonTheEyes** [comment]
Already an existing issue, submit updated info as comment to #673
