### ISSUE TITLE
Torchlight 2

### ISSUE THREAD

**Issue by yusopbalilo** [skyline-emu/skyline-games-list#1505]
Skyline Edge v56
Undocked to avoid fps drop usually in the cave or dungeon
Game is playable without any issue
Driver v615.50 vulkan driver-v1

On skyline edge v57
The game is not starting

![Screenshot_20230331-194836017](https://user-images.githubusercontent.com/81518480/229172430-f3199d38-8dac-4282-9c60-9d5c96cac13d.jpg)
![Screenshot_20230331-194900802](https://user-images.githubusercontent.com/81518480/229172474-481f0719-64ac-47db-986d-f3802ce77073.jpg)
![Screenshot_20230331-194944055](https://user-images.githubusercontent.com/81518480/229172527-d114808b-4258-4602-9570-234044f5e9c8.jpg)
![Screenshot_20230331-194956332](https://user-images.githubusercontent.com/81518480/229172587-649e03c6-c0f5-47fa-8617-0bb0edf20a04.jpg)
![Screenshot_20230331-195005987](https://user-images.githubusercontent.com/81518480/229172641-23da55c1-df91-4834-8a0f-183a72178502.jpg)
![Screenshot_20230331-195011039](https://user-images.githubusercontent.com/81518480/229172683-3bb5aca9-6f0b-4f53-b530-6bd52dfe7c62.jpg)
![Screenshot_20230331-195019234](https://user-images.githubusercontent.com/81518480/229172726-91799436-4be8-47f3-970c-f2adb45dded2.jpg)

**Comment by pdcmoreira** [comment]
Duplicated https://github.com/skyline-emu/skyline-games-list/issues/1092
