### ISSUE TITLE
Blaster Master Zero

### ISSUE THREAD

**Issue by Ibrohim112** [skyline-emu/skyline-games-list#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-65

### Android Version

11

### SoC type

Exynos

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s10-9536.php

### Game Behaviour

Status-Nothing
"- Version 1.0.0 or neither 1.5.2 doesn't boot. Short speaking, instant crash when opening.

Please support this game as it is first game before it's sequels Blaster Master Zero 2 and Blaster Master Zero 3

Here is 1.5.2 version
![Screenshot_20230417-152253](https://user-images.githubusercontent.com/94105067/232457639-93821cc3-c75f-4486-b9c4-6c7b4148de61.png)

Here is video:

https://user-images.githubusercontent.com/94105067/232459651-90dfd457-bd94-43d9-8ff1-f240c6828c25.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/11248999/emulation.zip)

**Comment by Ibrohim112** [comment]
status-nothing label

**Comment by K11MCH1** [comment]
@Ibrohim112  An issue of this game already exists.
Please use the search tool before acknowledging having searched for it next time...

**Comment by Ibrohim112** [comment]
Does this mean it never be played?
