### ISSUE TITLE
The legend of Zelda:Link's awakening

### ISSUE THREAD

**Issue by gamerto993** [skyline-emu/skyline-games-list#1545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

2419

### Android Version

13

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_a53_5g-11268.php

### Game Behaviour

![Screenshot_20230417_163051](https://user-images.githubusercontent.com/79471232/232500976-3b8a65cc-ebbd-4d46-af14-4ecc6225440c.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/11250760/emulation.sklog.txt)

**Comment by K11MCH1** [comment]
@gamerto993 There's already an existing issue for this game.
Please use the search tool before acknowledging you have done so in the issue form next time...
