### ISSUE TITLE
Super Mario 3D World

### ISSUE THREAD

**Issue by pocketm337** [skyline-emu/skyline-games-list#1550]
The Controls are not working when I launch the game. I see others Playing it fine and am wondering what I'm doing wrong?

**Comment by lazimk** [comment]
There is already an issue open for Super mario 3D world + Bowser's fury.

Coming to your problem, try setting controller type to 'Pro controller' from settings and launch the game

**Comment by pocketm337** [comment]
I tried that, but it didn't work.

**Comment by K11MCH1** [comment]
Do not create post without the form. This section is for compatibility reporting only.
Furthermore, an issue already exists for this game.

**Comment by locoper2255** [comment]
Como lo intalo
