### ISSUE TITLE
Make the driver for mali gpu 

### ISSUE THREAD

**Issue by Spidey2247** [skyline-emu/skyline-games-list#1556]
Can anyone create mali gpu driver for mediatek or not ,then tell me how to create I'll make

**Comment by iniMerchant64** [comment]
Neither we nor you can make a driver for a Mali GPU. ARM makes them and you could make a pkg for adrenotools however there is no difference between newer and older Mali drivers. Only custom one called PanVk is ages away from being usable let alone good
