### ISSUE TITLE
<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by Yarianni** [skyline-emu/skyline-games-list#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Esta

### Android Version

12

### SoC type

Other

### Device GSMArena link

Ver

### Game Behaviour

Estaversion

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Version

**Comment by K11MCH1** [comment]
????
