### ISSUE TITLE
A<Full game name displayed in skyline>

### ISSUE THREAD

**Issue by diego10ak** [skyline-emu/skyline-games-list#1583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

A

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

A

### Game Behaviour

L

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

S

**Comment by guranu** [comment]
@K11MCH1 remove these issues.
