### ISSUE TITLE
The Legend of Zelda: Tears of the Kingdom

### ISSUE THREAD

**Issue by Darthwayne** [skyline-emu/skyline-games-list#1602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-72

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/asus_rog_phone_6-11647.php

### Game Behaviour

Nothing, black screen. No FPS or GPU usage.

https://youtu.be/n4OoeK6iYS4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/11370346/emulation.zip)

**Comment by bylaws** [comment]
Piracy is not supported
