### ISSUE TITLE
The Legend of Zelda: Tears of the Kingdom

### ISSUE THREAD

**Issue by Thepowa753** [skyline-emu/skyline-games-list#1603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#2498

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_12_pro-11287.php

### Game Behaviour

Not Booting. Black screen 0 FPS.

Settings:
- Audio: OFF
- Executor slots: 4
- GPU send freq: 380
- Direct Memoty: ON
- Max GPU freq: ON
![photo_2023-05-02_05-51-16](https://user-images.githubusercontent.com/44495483/235635691-2d4aa94a-af23-4173-8594-1f1b1dee7c87.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/11371965/emulation.sklog.txt)

**Comment by K11MCH1** [comment]
@Thepowa753 Blocked from this repository for posting info on a leaked game.
