### ISSUE TITLE
Pokemon Shield 

### ISSUE THREAD

**Issue by Aaryik7464** [skyline-emu/skyline-games-list#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-3

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s22_ultra_5g-11251.php

### Game Behaviour

oh mu

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

hello

**Comment by TheASVigilante** [comment]
🗿

**Comment by Rajeshdey510** [comment]
The Skyline emulator is crash when I evolve charmeleon in pokemon let's go Pikachu

Phone name- vivoy22
Ram-6gb
Storage-128gb
Android version-13

**Comment by Crytonics** [comment]
Duplicate of #1400

**Comment by neostasha** [comment]
How to download this game
