### ISSUE TITLE
There is no game: Wrong dimension

### ISSUE THREAD

**Issue by Hedd-666-22** [skyline-emu/skyline-games-list#1612]
![Screenshot_20230504-104532](https://user-images.githubusercontent.com/132582919/236229901-ff9d0d02-d6d7-41c9-8825-24f2a955028b.png)
![Screenshot_20230504-105038](https://user-images.githubusercontent.com/132582919/236229922-d85d252d-0b59-45d6-9f68-38967895f8f8.png)
![Screenshot_20230504-105056](https://user-images.githubusercontent.com/132582919/236229944-007c5106-be78-47d8-be28-7d985af95b3e.png)
O jogo roda no Skyline (EDGE), mas os sprites ficam praticamente pretos, não podendo ver eles, ou seja praticamente impossível de jogar

**Comment by Crytonics** [comment]
Please use the correct format.
