### ISSUE TITLE
The Binding of Isaac: Afterbirth Plus 

### ISSUE THREAD

**Issue by AndreHero007** [skyline-emu/skyline-games-list#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s20_fe-10428.php

### Game Behaviour

Game instantly closes when opened

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8608432/emulation.zip)

**Comment by iniMerchant64** [comment]
36-bit. We already have this game listed as playable (after updates)
