### ISSUE TITLE
Slime lancher plortable edition

### ISSUE THREAD

**Issue by kareemnew2019** [skyline-emu/skyline-games-list#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

### Game Behaviour

Ing

https://user-images.githubusercontent.com/78564582/166416072-7dca5e5a-0bda-45f0-99bd-33b4f9805075.mp4

Freeze in game screen

With about 3 fps in docked mode and 12 fps in undocked mode
Snapdragon 732g
A52
Doesn't start

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

.

**Comment by K11MCH1** [comment]
Didn't attach zipped log file.
