### ISSUE TITLE
Slime Rancher plortable edition with log

### ISSUE THREAD

**Issue by kareemnew2019** [skyline-emu/skyline-games-list#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

### Game Behaviour

Freeze in menu screen

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

# Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

Freeze in menu screen

With about 3 fps in docked mode and 12 fps in undocked mode
Snapdragon 732g
A52
Doesn't start

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8612612/emulation.sklog.zip)

**Comment by Aztroloe** [comment]
💀

**Comment by kareemnew2019** [comment]
What

**Comment by kareemnew2019** [comment]
How did I break it
