### ISSUE TITLE
Games i tried and crashed

### ISSUE THREAD

**Issue by kareemnew2019** [skyline-emu/skyline-games-list#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

### Game Behaviour

Intro or does even start
( I made it so people avoid that game so he does get sad when it crash on him )
If anybody have time and have these games please comment Logs so you help the devs
And I will try to update it as i try more games 💓
1 : minecraft switch edition (dead)
2 : terraria (intro)
3 : super meat boy (dead)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I accidentally deleted them
( please don't close it because I want people to know the games that crash )
And thank you for delivering us skyline

**Comment by K11MCH1** [comment]
Thank you for your concern! :)

But 1 game per issue. Also please check other people's issues and take note on the formatting, detailing of the issues.
Always add a zipped log file.

Thank you!

**Comment by kareemnew2019** [comment]
Ok no problem 💓💓
