### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by kareemnew2019** [skyline-emu/skyline-games-list#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1067

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_a52-10641.php

### Game Behaviour

Low frame rate
A lot of graphical errors
Nearly unplayable [99%]

https://user-images.githubusercontent.com/78564582/166564066-399cf521-0caf-4e9d-9076-69a81f1d77e9.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8614235/emulation.sklog.zip)

**Comment by PixelyIon** [comment]
@kareemnew2019 Why was this closed? We generally keep game issues open always even if there are no issues, just because they may pop up in the future.

**Comment by kareemnew2019** [comment]
I updated it

**Comment by kareemnew2019** [comment]
Rereported it

**Comment by PixelyIon** [comment]
@kareemnew2019 Ah, there's no need to create a new issue every time, you can simply drop a comment on the older one. I will be closing this one anyway since it's superseded by #351.

**Comment by kareemnew2019** [comment]
And sorry I upset you I will never close a issue if I didn't forget
❤️

**Comment by kareemnew2019** [comment]
Ok ❤️
