### ISSUE TITLE
NeoGeo Colection n1

### ISSUE THREAD

**Issue by darkeholy** [skyline-emu/skyline-games-list#254]
The game was playable in previous Skyline version with low speed but now is Black screen

**Comment by HalogenGam3r** [comment]
If you have a Mali GPU, I advise you to wait until the issue is fully fixed.

**Comment by darkeholy** [comment]
> If you have a Mali GPU, I advise you to wait until the issue is fully fixed.

My GPU is a Adreno um using a Poco X3 Pro and tested even others stand alone game of this collection

**Comment by Crytonics** [comment]
If you have problem with Skyline or games go to https://github.com/skyline-emu/skyline or ask on discord server for help.
