### ISSUE TITLE
Adventure Time: Pirates Of Enchiridion 

### ISSUE THREAD

**Issue by Sebastian1332** [skyline-emu/skyline-games-list#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1087

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_a52-ampp-10641.php

### Game Behaviour

-Black Screen
-Only cartoon network sound works

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

https://mega.nz/file/URlSiB5Q#V4pYNJ1OJhlVPq1FXABimeC3NDexv5a4vgJUdE58rqU

**Comment by iniMerchant64** [comment]
The game was reported to the repo twice. Closing this one as the other one is more up-to-date
