### ISSUE TITLE
Dragons Dogma

### ISSUE THREAD

**Issue by Zolf666** [skyline-emu/skyline-games-list#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1109

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f3-10758.php

### Game Behaviour

Boot initial logo with glitch and initial settings
Crash after finishing the initial settings
Audio working
![Screenshot_2022-05-14-13-46-58-698_com google android apps photos](https://user-images.githubusercontent.com/59439763/168441239-18251f81-aef8-434a-b53f-e9339b60c0a4.jpg)
![Screenshot_2022-05-14-13-47-17-467_com google android apps photos](https://user-images.githubusercontent.com/59439763/168441241-11487ec6-49b9-4208-819e-eb49ebc25572.jpg)

### Is Log Level is set to 'Info'?

- [x] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8693558/emulation.zip)

**Comment by K11MCH1** [comment]
Hi,

Please retest with the latest build.

Thanks!

**Comment by K11MCH1** [comment]
This game had already been posted.
Please use the filter bar to look up games before posting, please.

Thanks.
