### ISSUE TITLE
Hatsune Miku Project DIVA Mega Mix - 01001CC00FA1A000

### ISSUE THREAD

**Issue by FensBK** [skyline-emu/skyline-games-list#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1092

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s20_fe_2022-11459.php

### Game Behaviour

The game doesn't boot, black screen then crashes.
![Screenshot_20220511-113732_Skyline](https://user-images.githubusercontent.com/67829964/167876782-8aaa470e-41f1-491f-a1db-df09784e7156.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8670845/emulation.zip)

**Comment by Aztroloe** [comment]
Game is already on the list
