### ISSUE TITLE
Arcaea

### ISSUE THREAD

**Issue by ActualMandM** [skyline-emu/skyline-games-list#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1107

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_s22+_5g-11252.php

### Game Behavior

- Only displays a black screen, no audio output

Screenshot of game:
![Screenshot_20220513-195305_Skyline](https://user-images.githubusercontent.com/15317421/168408215-21dee252-8bf0-43ca-ae37-86fece67fb8e.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8692029/emulation.sklog.zip)

**Comment by ActualMandM** [comment]
### Tested Build

1107

### Game Behavior

- Only displays a black screen

Screenshot of game:
![Screenshot_20220513-195305_Skyline](https://user-images.githubusercontent.com/15317421/168408215-21dee252-8bf0-43ca-ae37-86fece67fb8e.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8692029/emulation.sklog.zip)

**Comment by Crytonics** [comment]
Retest with latest build tnx.

**Comment by guranu** [comment]
@ActualMandM please test Arcaea on build 1254 with custom drivers.

**Comment by ActualMandM** [comment]
Currently unable to test, reopen the other issue.

**Comment by mr-hopeless** [comment]
> please test Arcaea on build 1254 with custom drivers.

You can post your results here.

**Comment by guranu** [comment]
ok here:

https://user-images.githubusercontent.com/103632948/181713967-5d696922-742e-49a8-918a-35d5f591ece7.mp4
