### ISSUE TITLE
Touhou Luna Nights

### ISSUE THREAD

**Issue by nekomekoraiyuu** [skyline-emu/skyline-games-list#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1353 - ftx1

### Android Version

13 (Tiramisu)

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour And issues:
- Good audio
- Mild graphical bugs (water texture is missing)
- Game boots up but start screen bg isn't visible
- Game is very playable (58-60ish fps)
- Cannot save after the first save (Scroll below for detailed demonstration + Workaround)

### Attachments:
![Screenshot_20220924-120053_Skyline](https://user-images.githubusercontent.com/45197348/192085608-cb305100-457e-4da8-898a-090a6a0597af.png)
> `Start screen`

![Screenshot_20220924-132242_Skyline](https://user-images.githubusercontent.com/45197348/192085894-5f36b927-2a31-4b12-b136-8c3dd9ef040b.png)
> `Main menu`

![Screenshot_20220924-132247_Skyline](https://user-images.githubusercontent.com/45197348/192085680-c7b6ef22-fa40-485a-b10f-b5ed314d5fce.png)
> `Save selection screen`

https://user-images.githubusercontent.com/45197348/192085646-2bac9bdc-676c-4e8a-a489-88befbf67fd7.mp4

> `Gameplay`

https://user-images.githubusercontent.com/45197348/192085719-ca80c3db-7a35-4697-a09f-87232d088599.mp4
> `Cannot load saves demonstration`

### Fixing saves workaround:

https://user-images.githubusercontent.com/45197348/194346216-11e6fe38-dee9-4e32-9583-1d94a35b2d93.mp4
>`Please follow the steps shown in the video.`

Steps:
1. Come near a saving station and pause the game
2. Now open a file manager that can access android/data directory (I recommend using mixplorer) 
[Click here to download MiXplorer](https://github.com/skyline-emu/skyline-games-list/files/9725870/MiXplorer_v6.58.5_B22090510.zip)
3. Now open the specified directory: `/storage/emulated/0/Android/data/skyline.emu/files/switch/nand/user/save/0000000000000000/00000000000000000000000000000001/0100D850131B0000`
4. Now delete the desired save file you want; 
Slot 1 = game0.sav
Slot 2 = game1.sav
Slot 3 = game2.sav
5. Now return to the game and touch the save station you should see the gave has been successfully saved.

### Is Log Level is set to 'Info'?

- [X] Yes

### Here are the logs:
[2hu LN Logs.zip](https://github.com/skyline-emu/skyline-games-list/files/9638148/2hu.LN.Logs.zip)

```
W1162HOS-0HandleRequest: Cannot find HIPC function in service 'hid::IHidServer': 0x1F (31)
```

```
W2662GPFIFOCompleteDma: Non-linear I2M uploads are not supported!
```

**Comment by xxRaiyanxxYT** [comment]
Game has been retested using newer build
+ Updated Logs

**Comment by raiyuulmao** [comment]
Game has been retested with the build-1206
👀

**Comment by dochankpin** [comment]
me too

**Comment by raiyuulmao** [comment]
Game has been retested with build #1256 + Custom Driver UI By Lynx
Please add "Ingame" Status and remove "Boots" Label
since the game boots up now with custom mesa turnip drivers though

**Comment by raiyuulmao** [comment]
Tested again waited newer #1353 build
+ Updated logs

**Comment by nekomekoraiyuu** [comment]
Updated the issue and added workarounds for the saving bug :>

**Comment by baderA34** [comment]
@nekomekoraiyuu Edge v11 fixes VFS, the game is now able to save and delete them at will properly

**Comment by nekomekoraiyuu** [comment]
@baderA34 i see good good
also if you own the game can you test it for me?
and update the issue temporarily here since I can't test since my phone is bricked yk

**Comment by baderA34** [comment]
@nekomekoraiyuu  yes I do own the game and I have tested it to confirm my previous comment. And if you are wondering, yes I am also a member of the edge users.

I've also tested other titles, you can check my issues if any interests you.

There's one I want to make for Scarlet Symphony, but I'm done with it.

**Comment by nekomekoraiyuu** [comment]
@baderA34 i've checked your other issues very certified tahoe gameplay
so i wonder if i should close the issue since its not being updated anymore (aka. can't test anymore due to device brick) 
i could request you to make a new issue for this game if you don't mind and closing this issue ;-;

**Comment by baderA34** [comment]
@nekomekoraiyuu sure I'll try my best and thank you for your kind words.

You can either talk to one of the moderators to close this issue or you can do it yourself (I think). Either way I'll get it done.

**Comment by nekomekoraiyuu** [comment]
@baderA34 okie thanks i appreciate it i'll be soon closing this issue temporarily as soon as you're done xd

**Comment by nekomekoraiyuu** [comment]
This issue has been closed temporarily and
moved to #1303
