### ISSUE TITLE
Katana Zero

### ISSUE THREAD

**Issue by ManoItachiOFC** [skyline-emu/skyline-games-list#367]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Tested Build

1109

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_redmi_note_11-11336.php

### Game Behaviour

Katana Zero started but the Menu has graphical bugs but it works and I even managed to play, the level was right but it had only some graphical bugs, and the characters had a black square on them.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

![20220515_114529](https://user-images.githubusercontent.com/103621819/168479411-10390a7c-6aaf-4093-a21b-cc9a305636ea.jpg)

**Comment by K11MCH1** [comment]
Greetings,

Katana Zero was already posted.
Please use the search tool (Filters) to look up the game before posting. If there is already an existing post for the game, please add the issues that you experience in the Comment section.

Thank you.
