### ISSUE TITLE
Blasphemous

### ISSUE THREAD

**Issue by masterpiece67** [skyline-emu/skyline-games-list#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1109

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

Setting: default
Status: Can enter the game
fps: 20 - 30
Docked mode on: in the game
Docked mode off: stuck open save state

Docked mode: On
![Screenshot_2022-05-16-00-53-06-670_skyline emu](https://user-images.githubusercontent.com/92961132/168484759-5a29d940-fd50-4e45-ad7f-84b4ad40462e.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Blasphemous.zip](https://github.com/skyline-emu/skyline-games-list/files/8695476/Blasphemous.zip)

**Comment by K11MCH1** [comment]
Greetings,

Blasphemous was already posted.
Please use the search tool (Filters) to look up the game before posting. If there is already an existing post for the game, please add the issues that you experience in the Comment section.

Thank you.
