### ISSUE TITLE
Metroid Dread

### ISSUE THREAD

**Issue by masterpiece67** [skyline-emu/skyline-games-list#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1109

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

Setting: Default
Status: enter the menu, the sound is heard but black screen
fps: lock to 60
Docked mode on: sound heard, black screen
Docked mode off: it same

![Screenshot_2022-05-16-01-18-00-689_skyline emu](https://user-images.githubusercontent.com/92961132/168485932-b41e80c3-413f-4d0b-bd10-e1067b20400e.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[metroid dread docked mode_on.zip](https://github.com/skyline-emu/skyline-games-list/files/8695561/metroid.dread.docked.mode_on.zip)

**Comment by K11MCH1** [comment]
Greetings,

Metroid Dread was already posted.
Please use the search tool (Filters) to look up the game before posting. If there is already an existing post for the game, please add the issues that you experience in the Comment section.

Thank you.
