### ISSUE TITLE
Akane

### ISSUE THREAD

**Issue by masterpiece67** [skyline-emu/skyline-games-list#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1158

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

•Bad performace lock 8-10 fps
•non graphical issue
![Screenshot_2022-06-02-04-34-47-632_skyline emu](https://user-images.githubusercontent.com/92961132/171497318-eb4b391d-16ba-4869-8824-fcb1e76e4c2c.jpg)
![Screenshot_2022-06-02-04-35-08-227_skyline emu](https://user-images.githubusercontent.com/92961132/171497332-75ad3f2f-0434-4be8-992c-520d088aceaa.jpg)
![Screenshot_2022-06-02-04-35-14-304_skyline emu](https://user-images.githubusercontent.com/92961132/171497347-a12c3f92-3703-44c9-8ae0-b70027a619ea.jpg)
![Screenshot_2022-06-02-04-35-19-363_skyline emu](https://user-images.githubusercontent.com/92961132/171497650-6f3cb1e4-66d4-4865-bde8-000f24f665d6.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Akane.zip](https://github.com/skyline-emu/skyline-games-list/files/8818611/Akane.zip)

**Comment by dimaxdqwerty** [comment]
Issue already exists. Pls check before creating issues (you even have checkbox for that)
