### ISSUE TITLE
Minecraft Dungeons 

### ISSUE THREAD

**Issue by Joemama45** [skyline-emu/skyline-games-list#534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1169

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/samsung_galaxy_tab_s7-10337.php

### Game Behaviour

- The game doesn't boot at all
- No Sound 
- No start up menu
- Crashes 
![Picsart_22-06-04_15-17-14-979](https://user-images.githubusercontent.com/97562949/172022498-18e33c04-ed05-46f7-b71d-f8869a13851d.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by K11MCH1** [comment]
Please post the log file.
If you're having trouble uploading the file, try changing the extension to .txt.

**Comment by K11MCH1** [comment]
@Joemama45 You have been banned from this repository.
Reason: Found illegal website in the logs.

**Comment by 1ndenas** [comment]
When will the game work? I really like this game :D
