### ISSUE TITLE
Vigil The longest Night

### ISSUE THREAD

**Issue by yhak22** [skyline-emu/skyline-games-list#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1112 and latest

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/lg_v60_thinq_5g-10103.php

### Game Behaviour

Unity Game 

1112
the game kinda playable, some graphical issues, no audio , fps drops, rng.
![Screenshot_20220603-191836](https://user-images.githubusercontent.com/23446817/172041606-56919b60-b7b2-448c-b382-a7f8b5a68e48.png)
![Screenshot_20220603-191641](https://user-images.githubusercontent.com/23446817/172041628-f253eced-95d4-4337-b7a7-dd4bed313268.png)
![Screenshot_20220603-193236](https://user-images.githubusercontent.com/23446817/172041641-d4dbc3d0-f774-47ad-99cf-5fdf9f2771a8.png)

1168

the game crash on docked.
on handheld after some try it enter the game but alot of graphical issues, character face black , some broken effect, fps drops
and some ui broken Like map, after some play it crashed.

![Screenshot_20220603-231639](https://user-images.githubusercontent.com/23446817/172041707-23d798fa-8662-42ef-9518-f2ee2cb317e2.png)
![Screenshot_20220603-231720](https://user-images.githubusercontent.com/23446817/172041721-9328fc50-889c-494e-b525-ceb72bd83b75.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file
[1112.zip](https://github.com/skyline-emu/skyline-games-list/files/8839543/1112.zip)
[1168.zip](https://github.com/skyline-emu/skyline-games-list/files/8839544/1168.zip)

**Comment by yhak22** [comment]
Oh sorry there is an issues already for this game i can't delete this issue.

**Comment by MuhSlam** [comment]
You can closed this issue if already exist
By click three dot above ( on github app )
