### ISSUE TITLE
Little nightmares

### ISSUE THREAD

**Issue by 13gkd** [skyline-emu/skyline-games-list#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1174

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

Poco f1

### Game Behaviour

![Screenshot_2022-06-05-16-10-42-623_skyline emu](https://user-images.githubusercontent.com/103353628/172046665-a56dd2e5-ea77-4d7a-9906-3faffce2ef7e.jpg)
![Screenshot_2022-06-05-16-10-30-158_skyline emu](https://user-images.githubusercontent.com/103353628/172046668-549d8217-3349-4260-8419-55373e500858.jpg)
Game crash

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Not playable

**Comment by K11MCH1** [comment]
Issue of this game already exists. Please use the search tool before posting.
If an issue already exists, post your experiences in the comment section.
