### ISSUE TITLE
Adabana Odd Tales

### ISSUE THREAD

**Issue by miko4002** [skyline-emu/skyline-games-list#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1174

### Android Version

11

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_a12-10604.php

### Game Behaviour

- Black Screen
- No Audio
![Screenshot_20220605-230225_Skyline](https://user-images.githubusercontent.com/78865865/172059520-b8e075a1-e64d-40f0-a85e-60f149772b3b.jpg)

### Is Log Level is set to 'Info'?

- [x] Yes

### Log file

[emulation.zip](https://drive.google.com/file/d/1Z_ucfINrSAtdaI5-bMKds6eV4OjRVIQJ/view?usp=drivesdk)

**Comment by Crytonics** [comment]
@K11MCH1  @Sovietfowl  link in log

**Comment by K11MCH1** [comment]
@miko4002 You have been banned from this repository for posting a log with an illegal link.

**Comment by Crytonics** [comment]
@K11MCH1 you didn't remove log
