### ISSUE TITLE
Minecraft Dungeons 

### ISSUE THREAD

**Issue by Aboodal7asan** [skyline-emu/skyline-games-list#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

0.0.3

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f3-10758.php

### Game Behaviour

Minecraft dungeons runs for a second then stops at a black screen
It shows that some frames have been processed but then it freezes at a black screen

![Screenshot_20220606-122844_Skyline](https://user-images.githubusercontent.com/95929815/172136014-bf35343d-885f-408b-a966-73b1f2c3b7f3.png)

Request to add an option to control the game resolution it will help in terms of performance

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/8843406/emulation.txt)

**Comment by Aboodal7asan** [comment]
Skyline version: 0.0.3
Game version: 1.10.3.0

**Comment by Mr-Hopeless** [comment]
> Skyline version: 0.0.3
> Game version: 1.10.3.0 

Hey there. You're supposed to add the CI number instead of version.

**Comment by K11MCH1** [comment]
An issue for this game already exists. Only 1 issue per game allowed. Use the search function before posting an issue.

**Comment by Aboodal7asan** [comment]
Yeah but you banned that guy because he downloaded tbe game from a website

**Comment by Crytonics** [comment]
> Yeah but you banned that guy because he downloaded tbe game from a website

Mods can edit others issues, so it's fine.

**Comment by Skeliton001** [comment]
I really need this game to run, please im counting on you all 😃
