### ISSUE TITLE
Guns, Gore And Cannaoli 2

### ISSUE THREAD

**Issue by sadaqali** [skyline-emu/skyline-games-list#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

I don't know

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/oneplus_nord_2_5g-10960.php

### Game Behaviour

![Screenshot_2022-06-09-19-35-04-35_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/107110808/172949653-d0ab7ffa-34ed-4ebe-8fad-6c729c78e1ed.jpg)
![Screenshot_2022-06-09-19-45-56-67_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/107110808/172949664-dac74d6a-218d-4b3a-a319-f5587731709a.jpg)

While game start up it is lagging so much. I had to press the control many times to select option and during gameplay there is one white block is popping up 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8874149/emulation.zip)

**Comment by MuhSlam** [comment]
This game list already exist
https://github.com/skyline-emu/skyline-games-list/issues/224
Use search tool next time , if want to post
