### ISSUE TITLE
Angry video game nerd I & II deluxe

### ISSUE THREAD

**Issue by Vertimusmaximus** [skyline-emu/skyline-games-list#596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_s10-9536.php

### Game Behaviour

Boots and stays in black screen. No audio. No fps. 

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by Sovietfowl** [comment]
Your log contains a piracy website name, you are banned from the repository.

**Comment by TheKing221160** [comment]
> Your log contains a piracy website name, you are banned from the repository. 

I see you everywhere Sir is your task to check every log file and see them

**Comment by bylaws** [comment]
> > Your log contains a piracy website name, you are banned from the repository.
> 
> I see you everywhere Sir is your task to check every log file and see them

You would be correct, it is his only task as an employee of Markus Tech LLC.

**Comment by Sovietfowl** [comment]
This is true

**Comment by TheKing221160** [comment]
> > > Your log contains a piracy website name, you are banned from the repository.
> > 
> > I see you everywhere Sir is your task to check every log file and see them
> 
> You would be correct, it is his only task as an employee of Markus Tech LLC. 

Thanks Sir for the answer
