### ISSUE TITLE
CARDFIGHT!! VANGUARD EX

### ISSUE THREAD

**Issue by spadeshiro** [skyline-emu/skyline-games-list#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

Overall, game will boot and lets you do everything if it doesn't freeze in a decent framerate (title and dialogue will run around 57fps, duel around 30 to 40fps)

Several issues I found:
- BGM seems to be slightly slowed down in certain places, like somewhere around 5 to 10% slower
- dialogue box is broken, card information box is also broken, otherwise every other interfaces are working as expected
- game will freeze, either [during start screen or duel](https://streamable.com/p00a7l). Freezing always happen during duel (and a rather high chance on start screen), be it on the very beginning or at the middle of the fight, making the game impossible to progress.

Screenshot of the issue (left being Skyline, and right being Ryujinx for comparison):
![screenshot 1](https://user-images.githubusercontent.com/25726032/173229095-8b57edec-9029-403d-99c2-927879dc4d40.jpg)
![screenshot 2](https://user-images.githubusercontent.com/25726032/173229101-c2bd8404-2e35-459d-b543-b8aea4f5e056.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Crytonics** [comment]
```
W292HOS-0HandleRequest: Cannot find function in service 'visrv::IApplicationDisplayService': 0x836 (2102)
```

**Comment by Sovietfowl** [comment]
Your log contains a name of a piracy website, you're banned from the repository.
