### ISSUE TITLE
Sword Art Online: Hollow Realization Deluxe Edition 

### ISSUE THREAD

**Issue by EduardoDuran0502** [skyline-emu/skyline-games-list#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1201

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-ampp-10802.php

### Game Behaviour

![Screenshot_2022-06-12-11-33-58-588_skyline emu](https://user-images.githubusercontent.com/91035758/173243461-6f13d324-ff4c-4e0d-9b33-3b3c346b1b52.jpg)

The Screen Stay black and nothing else happen

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I38EmuMainApplyDriverPatches: Applied BCeNabler patch
I39EmuMainCreateDevice: Vulkan Device:
Name: Adreno (TM) 640
Type: IntegratedGpu
Driver ID: QualcommProprietary
Vulkan Version: 1.1.128
Driver Version: 0.502.0
Queues:
* 3xGC--P: TSB48 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_KHR_shared_presentable_image (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_KHR_external_memory (v0.0.1)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_EXT_fragment_density_map (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_QCOM_render_pass_store_ops (v0.0.2)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_QCOM_render_pass_shader_resolve (v0.0.4)
* VK_KHR_maintenance1 (v0.0.1)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_KHR_sampler_ycbcr_conversion (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_push_descriptor (v0.0.1)
* VK_EXT_device_memory_report (v0.0.1)
* VK_KHR_device_group (v0.0.2)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_EXT_pipeline_creation_cache_control (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_EXT_sampler_filter_minmax (v0.0.1)
* VK_QCOM_render_pass_transform (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_EXT_texture_compression_astc_hdr (v0.0.1)
* VK_EXT_global_priority (v0.0.2)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_EXT_line_rasterization (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_dedicated_allocation (v0.0.1)
* VK_KHR_swapchain (v0.0.70)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: true
* Supports Custom Border Color (Without Format): false
* Supports Anisotropic Filtering: true
* Supports Last Provoking Vertex: false
* Supports Logical Operations: false
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
* Supports Push Descriptors: true
* Supports Imageless Framebuffers: false
* Supports Global Priority: true
* Supports Multiple Viewports: false
* Supports Shader Viewport Index: false
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: false
* Supports 16-bit FP: true
* Supports 8-bit Integers: true
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: false
* Supports Patch List Primitive Topology Restart: false
* Supports Subgroup Vote: true
* Subgroup Size: 64
* BCn Support: [1111111](tel:1111111)
Quirks:
* Needs Individual Texture Binding Writes: true
* VkImage Mutable Format is costly: true
* Adreno Relaxed Format Aliasing: true
* Adreno Broken Format Reporting: true
* Broken Descriptor Aliasing: true
* Relaxed Render Pass Compatibility: true
* Max Subpass Count: 64
* Max Global Queue Priority: High
I95EmuMainLaunching ROM content://com.android.externalstorage.documents/tree/primary%3AGamesSwitch/document/primary%3AGamesSwitch%2FSWORD%20ART%20ONLINE%20Hollow%20Realization%20Deluxe%20Edition%20%5B0100EC400D54E000%5D%5Bv0%5D(nsw2u).xci
I115EmuMainLoadExeFs: Loaded 'rtld.nso' at [0x800000000](tel:09800000000) (.text @ [0x800001000](tel:09800001000))
I234EmuMainLoadExeFs: Loaded 'main.nso' at [0x800005000](tel:09800005000) (.text @ [0x800006000](tel:09800006000))
I271EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x801D1C000 (.text @ 0x801D1D000)
I335EmuMainLoadExeFs: Loaded 'subsdk1.nso' at [0x802415000](tel:09802415000) (.text @ [0x802416000](tel:09802416000))
I388EmuMainLoadExeFs: Loaded 'sdk.nso' at [0x803240000](tel:09803240000) (.text @ [0x803241000](tel:09803241000))
I431HOS-0ICommonStateGetter: Switch to mode: Docked
I1390HOS-0SetPerformanceConfiguration: Performance configuration set to [0x20004](tel:0920004) (Handheld)
I1390HOS-0SetPerformanceConfiguration: Performance configuration set to [0x10001](tel:0910001) (Docked)
W1465HOS-0HandleRequest: Cannot find function in service 'visrv::IApplicationDisplayService': 0x836 (2102)
W1753HOS-0Disconnect: Disconnecting from API 'CPU' while connected to 'None'
W2116GPFIFOSetProvokingVertex: Cannot set provoking vertex to last without host GPU support
W2118HOS-0HandleRequest: Cannot find function in service 'hid::IHidServer': 0x5B (91)
I2276HOS-0pole4_EU:MainThread:[575877](tel:575877)s: PNamedSemanticDynamic::FindOrCreateDynamic : Performance warning - allocating freelist on demand for 'GenerateLightingTiledMorp
I2276HOS-0 heus'.
E10207HOS-8Signal: Bus error (PC: 0x7E176DD580) (SVC: SvcWaitSynchronization)
Stack Trace:
* 0x7E176DD580 (from [libskyline.so](http://libskyline.so/))
* 0x7E1770F8F4 (skyline::kernel::svc::WaitSynchronization(skyline::DeviceState const&) from [libskyline.so](http://libskyline.so/))
* 0x7E176EFE40 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from [libskyline.so](http://libskyline.so/))
* [0x8032400](tel:098032400)B8 (from sdk.nso.patch)
* 0x8006B93BC (from main.nso)
* 0x8006BF260 (from main.nso)
* 0x8000F4B70 (from main.nso)
* 0x8032F0868 (from sdk.nso)
* 0x8032F4BC8 (from sdk.nso)
* 0x8032F4B50 (from sdk.nso)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a piracy website name.
