### ISSUE TITLE
Dust: An Elysian Tale

### ISSUE THREAD

**Issue by Werner1201** [skyline-emu/skyline-games-list#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

CI 1201 

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

- Makes a sound while starting if I keep spamming button A
- It starts directly on a green screen
- is kinda on title screen but it only shows a green screen

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8886313/emulation.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Werner1201** [comment]
> @Sovietfowl link in log

is the report structure correct? first time here.

**Comment by Sovietfowl** [comment]
You are banned form the repository because your log contains a piracy website name.
