### ISSUE TITLE
To the moon

### ISSUE THREAD

**Issue by sadaqali1** [skyline-emu/skyline-games-list#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1201

### Android Version

11

### SoC type

Mediatek

### Device GSMArena link

https://m.gsmarena.com/oneplus_nord_2_5g-10960.php

### Game Behaviour

-Screen is cracking
-Game stuck

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[TOTHEMOON.zip](https://github.com/skyline-emu/skyline-games-list/files/8888206/TOTHEMOON.zip)

https://user-images.githubusercontent.com/107385534/173288001-79037a71-f371-4888-9abd-b27815cad244.mp4

**Comment by Crytonics** [comment]
```
E39656GPFIFOIndexed quad conversion is not supported
Stack Trace:
* 0x7E2BDB0A58 (from libskyline.so)
* 0x7E2BDBD360 (skyline::soc::gm20b::engine::maxwell3d::Maxwell3D::HandleMethod(unsigned int, unsigned int) from libskyline.so)
* 0x7E2BDA656C (skyline::soc::gm20b::ChannelGpfifo::Process(skyline::soc::gm20b::GpEntry) from libskyline.so)
* 0x7E2BDA6114 (from libskyline.so)
* 0x7E2BDA5790 (skyline::soc::gm20b::ChannelGpfifo::Run() from libskyline.so)
* 0x7E2BDA5EF4 (from libskyline.so)
* 0x7F1D1DB920 (from libc.so)
* 0x7F1D17C014 (from libc.so)
```

**Comment by Crytonics** [comment]
@Sovietfowl @K11MCH1 link in log

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a piracy website name.

**Comment by Sovietfowl** [comment]
Markus tech trade secret.

**Comment by Sovietfowl** [comment]
A more professional answer would be check the line on ROM contents, if a website name is right after the game title it's pirated.
