### ISSUE TITLE
Breathedge

### ISSUE THREAD

**Issue by jurises99** [skyline-emu/skyline-games-list#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1201

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour
![Screenshot_20220615-081439_Skyline](https://user-images.githubusercontent.com/22735064/173710627-cd26590b-34fd-4998-bc22-172952abcf9a.png)

Boots with sound, but black screen
will test again with next latest build

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8904598/emulation.sklog.zip)

**Comment by nabokie** [comment]
Can you test Breathedge on build #1200 cause #1201 is considered a "troll" build.

**Comment by jurises99** [comment]
this is the Log I got in build 1200, still boots in black screen, but with sounds
[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8904943/emulation.sklog.zip)

**Comment by jurises99** [comment]
> Can you test Breathedge on build #1200 cause #1201 is considered a "troll" build.

this is the Log I got in build 1200, still boots in black screen, but with sounds
[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8904949/emulation.sklog.zip)

**Comment by DanXG790** [comment]
@Sovietfowl Illegal site in the log's

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a piracy website.
