### ISSUE TITLE
Pokémon Brilliant Diamond

### ISSUE THREAD

**Issue by IAL32** [skyline-emu/skyline-games-list#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_poco_f3-10758.php

### Game Behaviour

- Black screen when loading game
- Nothing else happens

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8940875/emulation.zip)

**Comment by IAL32** [comment]
Already existing: https://github.com/skyline-emu/skyline-games-list/issues/684

**Comment by Crytonics** [comment]
@QuackingCanary same here

**Comment by QuackingCanary** [comment]
@IAL32 your log contains a piracy website, you're banned from the repository
