### ISSUE TITLE
Deponia

### ISSUE THREAD

**Issue by GabiAle97** [skyline-emu/skyline-games-list#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

Https://www.gsmarena.com/motorola_moto_g9_plus-10432.php

### Game Behaviour

-Audio is laggy
-Saves don't work, when the game is launched and you want to load a previously saved game, it does not exist inside the game, but it does exist in the file system.
-Cutscenes freezes the game until skip ( + button)
<screenshot>![Screenshot_20220620-135236_Skyline](https://user-images.githubusercontent.com/43727640/174654065-cab94e2a-e204-4595-8861-9c046bbe58d5.png)<screenshot>
https://m.gsmarena.com/motorola_moto_g9_plus-10432.php

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation log.zip](https://github.com/skyline-emu/skyline-games-list/files/8942431/emulation.log.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by mr-hopeless** [comment]
@Crytonics link in log

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a piracy website name.
