### ISSUE TITLE
Gear club ulimited 2

### ISSUE THREAD

**Issue by SinUsername** [skyline-emu/skyline-games-list#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1237

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_p30_lite-9545.php

### Game Behaviour

It has sound problems and crashes when trying to launch the game or tutorial of the game (which is just finished loading) so I have seen. 
![Screenshot_20220708_113629_skyline emu](https://user-images.githubusercontent.com/94080806/178035135-47018a2c-71cd-4282-86a6-e9949bb82cc3.jpg)
![Screenshot_20220708_113757_skyline emu](https://user-images.githubusercontent.com/94080806/178035140-acd79435-b211-4828-8b10-523f77dfe733.jpg)
Test again in build 1237

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Github won't let me upload the log because it weighs a lot of 27mb 

![Screenshot_20220708_115725](https://user-images.githubusercontent.com/94080806/178037180-cb21a3a0-6946-40d8-adf1-74bb0993d598.jpg)

![Screenshot_20220708_115406_com opera browser](https://user-images.githubusercontent.com/94080806/178037305-84c36956-91f9-4d7f-baa6-663b733f08ae.jpg)

**Comment by dimaxdqwerty** [comment]
Already exists

**Comment by SinUsername** [comment]
Oh! Then look bad sorry
