### ISSUE TITLE
Candleman

### ISSUE THREAD

**Issue by SinUsername** [skyline-emu/skyline-games-list#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1237

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_p30_lite-9545.php

### Game Behaviour

Excellent sound, graphic errors And it crashes when starting the game or chapter 1.
![Screenshot_20220709_182141_skyline emu](https://user-images.githubusercontent.com/94080806/178125710-50927fef-cbd0-4eef-a8c9-d4a123461a48.jpg)
![Screenshot_20220709_182147_skyline emu](https://user-images.githubusercontent.com/94080806/178125712-18134e21-19db-4c94-9b12-040ff8815f41.jpg)
![Screenshot_20220709_182150_skyline emu](https://user-images.githubusercontent.com/94080806/178125713-a86226a1-5fe5-49bb-afbd-58d0ddcd6092.jpg)
![Screenshot_20220709_182156_skyline emu](https://user-images.githubusercontent.com/94080806/178125714-8440601d-c8ce-4395-8c8f-330d7f2a5d89.jpg)
![Screenshot_20220709_182218_skyline emu](https://user-images.githubusercontent.com/94080806/178125715-ea4eafa5-5905-40a4-8c91-ec0f8aa301dd.jpg)
![Screenshot_20220709_182226_skyline emu](https://user-images.githubusercontent.com/94080806/178125716-7132eb75-4acb-400b-8114-c12465902357.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/9078062/emulation.sklog.txt)

**Comment by K11MCH1** [comment]
There is already an existing issue of this game. Only 1 entry per game is needed.
Use the search function before posting.
https://github.com/skyline-emu/skyline-games-list/issues/550
