### ISSUE TITLE
LIVE A LIVE Demo

### ISSUE THREAD

**Issue by zander1995** [skyline-emu/skyline-games-list#859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1246

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

AYN Odin Pro (Not available on GSMArena)

### Game Behaviour

Black screen, immediately closes the app
![Screenshot_20220718-032552](https://user-images.githubusercontent.com/32889908/179493807-d47b2918-f190-4fe3-a05d-d0b40eea7fe1.png)
.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9131218/emulation.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log
