### ISSUE TITLE
Tails of Iron

### ISSUE THREAD

**Issue by GhostLm** [skyline-emu/skyline-games-list#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1254

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/tcl_10_5g_uw-10559.php

### Game Behaviour

GPU all driver test
Black screen and zero fps
![image](https://user-images.githubusercontent.com/103976700/180663376-73f366ce-4e09-4c81-8e28-09313fb83660.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9176556/emulation.zip)

```
W848HOS-0GetService: Service has not been implemented: "ldr:ro"
W848HOS-0HandleRequest: Cannot find function in service 'am::IApplicationFunctions': 0x16 (22)
```

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.
