### ISSUE TITLE
UnderMine

### ISSUE THREAD

**Issue by GhostLm** [skyline-emu/skyline-games-list#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1254

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/tcl_10_5g_uw-10559.php

### Game Behaviour

Gpu all drivers test
opens but freezes immediately
![image](https://user-images.githubusercontent.com/103976700/180663673-da5b55d0-d71a-4460-a9b3-ff4c11ec5ca1.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9176576/emulation.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Sovietfowl** [comment]
You have been banned from the repository because your log contains a name of a piracy website.
