### ISSUE TITLE
Door Kickers: Action Squad

### ISSUE THREAD

**Issue by GhostLm** [skyline-emu/skyline-games-list#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1254

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/tcl_10_5g_uw-10559.php

### Game Behaviour

GPU all driver test
Black screen and zero fps
![image](https://user-images.githubusercontent.com/103976700/180663979-4236279b-9411-48a4-a146-81e01d0474f4.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9176585/emulation.zip)

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.
