### ISSUE TITLE
RPG Maker MV

### ISSUE THREAD

**Issue by SinUsername** [skyline-emu/skyline-games-list#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1265

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_p30_lite-9545.php

### Game Behaviour

Displays the upload logo, then displays the black screen and to make a gray screen visible, then locks. 
![Screenshot_20220730_140900_skyline emu](https://user-images.githubusercontent.com/94080806/181947903-75f88777-086d-4696-bb11-841c40251656.jpg)
![Screenshot_20220730_140923_skyline emu](https://user-images.githubusercontent.com/94080806/181947928-3b066de7-38bf-4e4f-87a3-a729ebb09888.jpg)
![Screenshot_20220730_140931_skyline emu](https://user-images.githubusercontent.com/94080806/181947938-3421106c-dd39-4158-952b-041de28786eb.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/9227155/emulation.sklog.txt)

```
W2414HOS-0HandleRequest: Cannot find function in service 'visrv::IApplicationDisplayService': 0x836 (2102)
W3761HOS-30HandleRequest: Cannot find function in service 'fssrv::IFileSystem': 0x1 (1)
```

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.

**Comment by NotintoCode** [comment]
Why is it closing can you atleast also include this game 
even though that guy is pirating because like me i still need this to be able to play in andriod.

**Comment by NotintoCode** [comment]
If you're closing this, is this mean some games isn't supported in skyline? If so then what's the point of playing games using skyline then?

**Comment by guranu** [comment]
> Why is it closing can you atleast also include this game even though that guy is pirating because like me i still need this to be able to play in andriod.

Sir, the user that posted this is banned for piracy.

**Comment by NotintoCode** [comment]
Then it'll not be continued?

**Comment by NotintoCode** [comment]
Because if i submit same issue will i not be mark as duplicate?

**Comment by guranu** [comment]
I mean it's closed so maybe you could post it.

**Comment by Crytonics** [comment]
> Because if i submit same issue will i not be mark as duplicate?

If there isn't open issue for that game you can create new issue.
