### ISSUE TITLE
Fighting Ex Layer Another Dash

### ISSUE THREAD

**Issue by SinUsername** [skyline-emu/skyline-games-list#883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1265

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_p30_lite-9545.php

### Game Behaviour

It costs a lot to make the game show the image with the logo of the game, then crashes 
![Screenshot_20220730_194035_skyline emu](https://user-images.githubusercontent.com/94080806/182005249-f7640eab-ae7a-4d9e-b8f6-008e9fa26d25.jpg)
![Screenshot_20220730_195648_skyline emu](https://user-images.githubusercontent.com/94080806/182005250-e43b16f0-5fe2-460f-bb97-46756f0ead64.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by K11MCH1** [comment]
@SinUsername An illegal link has been found in your log. You are blocked from further posting in this repository.
