### ISSUE TITLE
After Press ZR and Z button game freeze

### ISSUE THREAD

**Issue by karmakarsouvik** [skyline-emu/skyline-games-list#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1058

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-10802.php

### Game Behaviour

When i Press ZR and Z button game freezing.
Game name - Assault Gunners HD Edition

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

 I15EmuMainApplyDriverPatches: BCeNabler skipped, blob BCN support is present
I15EmuMainCreateDevice: Vulkan Device:
Name: Adreno (TM) 640
Type: IntegratedGpu
Driver ID: QualcommProprietary
Vulkan Version: 1.1.128
Driver Version: 0.617.0
Queues:
* 3xGC--P: TSB48 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_KHR_shared_presentable_image (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_KHR_external_memory (v0.0.1)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_copy_commands2 (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_EXT_fragment_density_map (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_QCOM_render_pass_store_ops (v0.0.2)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_QCOM_render_pass_shader_resolve (v0.0.4)
* VK_KHR_maintenance1 (v0.0.1)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_EXT_image_robustness (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_shader_terminate_invocation (v0.0.1)
* VK_QCOM_fragment_density_map_offset (v0.0.1)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_KHR_sampler_ycbcr_conversion (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_push_descriptor (v0.0.1)
* VK_EXT_device_memory_report (v0.0.2)
* VK_KHR_imageless_framebuffer (v0.0.1)
* VK_KHR_device_group (v0.0.2)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_EXT_shader_atomic_float (v0.0.1)
* VK_EXT_custom_border_color (v0.0.12)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_EXT_fragment_density_map2 (v0.0.1)
* VK_QCOM_rotated_copy_commands (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_EXT_private_data (v0.0.1)
* VK_EXT_pipeline_creation_cache_control (v0.0.1)
* VK_EXT_robustness2 (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_EXT_sampler_filter_minmax (v0.0.1)
* VK_KHR_16bit_storage (v0.0.1)
* VK_KHR_pipeline_executable_properties (v0.0.1)
* VK_EXT_shader_demote_to_helper_invocation (v0.0.1)
* VK_QCOM_render_pass_transform (v0.0.2)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_EXT_blend_operation_advanced (v0.0.1)
* VK_EXT_provoking_vertex (v0.0.1)
* VK_KHR_8bit_storage (v0.0.1)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_EXT_texture_compression_astc_hdr (v0.0.1)
* VK_EXT_global_priority (v0.0.2)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_EXT_descriptor_indexing (v0.0.2)
* VK_KHR_synchronization2 (v0.0.2)
* VK_EXT_line_rasterization (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_dedicated_allocation (v0.0.1)
* VK_EXT_primitive_topology_list_restart (v0.0.2)
* VK_KHR_swapchain (v0.0.70)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: true
* Supports Custom Border Color (Without Format): true
* Supports Last Provoking Vertex: true
* Supports Logical Operations: false
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
* Supports Push Descriptors: true
* Supports Global Priority: true
* Supports Multiple Viewports: false
* Supports Shader Viewport Index: false
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: true
* Supports 16-bit FP: true
* Supports 8-bit Integers: true
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Int

**Comment by Aztroloe** [comment]
Can you change the name of the issue?

**Comment by Aztroloe** [comment]
Your log file is also cut off
