### ISSUE TITLE
Cuphead

### ISSUE THREAD

**Issue by Sirox228** [skyline-emu/skyline-games-list#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1269

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f2_pro-10220.php

### Game Behaviour

I searched for an issue about this game and there's one of it, but i need to report an issue.
• was working in old versions of skyline
• not working in current version (check tested build) in both handheld and docked modes, also i used default driver

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9271638/emulation.zip)

**Comment by Silverdragon122** [comment]
Please dont make duplicates

**Comment by Crytonics** [comment]
Duplicate of #23

**Comment by Crytonics** [comment]
You can post comment there

**Comment by maiodin** [comment]
The game doesnt auto save.
Other than that runs perfect with minor freezes.
Using samsung fold 2

**Comment by Isaac7800** [comment]
Hol

**Comment by Isaac7800** [comment]
Holl

**Comment by Isaac7800** [comment]
Holl

**Comment by Simplementemanuel** [comment]
Si tienes un SD680 no te recomiendo jugarlo ya que el teléfono puede crashearse

**Comment by Angelreyes182** [comment]
Como descargar
