### ISSUE TITLE
HOA

### ISSUE THREAD

**Issue by yoursangs** [skyline-emu/skyline-games-list#902]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Tested Build

1289

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/lg_v50_thinq_5g-9607.php

### Game Behaviour

![Screenshot_20220807-170422_Skyline](https://user-images.githubusercontent.com/110479138/183286068-c357ca95-6a96-4a05-965f-fd74de41c123.png)
Can't get into the game. My phone is unlocked and I'm using corvus os rom

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[logs.zip](https://github.com/skyline-emu/skyline-games-list/files/9276597/logs.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a website.
