### ISSUE TITLE
Subnautica Below Zero

### ISSUE THREAD

**Issue by GoldenBurnik** [skyline-emu/skyline-games-list#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1295

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour

Crash on startup
![hehebsjai](https://user-images.githubusercontent.com/110814965/183375135-4c3a7bda-27c1-4ecc-91a1-a9e422b15775.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[mulator.zip](https://github.com/skyline-emu/skyline-games-list/files/9280265/mulator.zip)

```
E30539GPFIFORun: Signal: Segmentation fault @ 0x8 (PC: 0x6484B68028)
Stack Trace:
* 0x6484B68028 (from notllvm-qgl.so)
```
```
E30553HOS-1Signal: Segmentation fault @ 0xFFFFFFFFFFFFFFF7 (PC: 0x6D0408E314) (SVC: SvcWaitSynchronization)
Stack Trace:
* 0x6D0408E314 (from libskyline.so)
* 0x6D0408D76C (skyline::kernel::svc::WaitSynchronization(skyline::DeviceState const&) from libskyline.so)
* 0x6D0406BAC4 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x8064AE0B8 (from sdk.nso.patch)
* 0x8067EEF64 (nn::os::detail::MultiWaitImpl::InternalWaitAnyImpl(bool, nn::TimeSpan) from sdk.nso)
* 0x8067EF1C8 (nn::os::detail::MultiWaitImpl::WaitAnyImpl(bool, nn::TimeSpan) from sdk.nso)
* 0x8067EB8D4 (from sdk.nso)
* 0x8067EB83C (from sdk.nso)
* 0x8067EB82C (from sdk.nso)
* 0x8067ED7A8 (from sdk.nso)
* 0x8067F1F74 (from sdk.nso)
* 0x8067F1F20 (from sdk.nso)
```

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.
