### ISSUE TITLE
The Survivalists

### ISSUE THREAD

**Issue by GoldenBurnik** [skyline-emu/skyline-games-list#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1295

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour

Boots, then freezes
![Screenshot_20220808-222525_Skyline](https://user-images.githubusercontent.com/110814965/183444339-41ea539c-e4f4-4165-a305-8ac84d7eac71.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Survimf.txt](https://github.com/skyline-emu/skyline-games-list/files/9282635/Survimf.txt)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a piracy website
