### ISSUE TITLE
The Long Dark

### ISSUE THREAD

**Issue by GoldenBurnik** [skyline-emu/skyline-games-list#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1295

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour

Black screen then crashes
![Screenshot_20220808-224855_Skyline](https://user-images.githubusercontent.com/110814965/183447088-e29642c6-bd4a-4088-9f86-effbfc410e35.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Longdarefx.txt](https://github.com/skyline-emu/skyline-games-list/files/9282737/Longdarefx.txt)

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.
