### ISSUE TITLE
Koumajou Remilia Scarlet Symphony 

### ISSUE THREAD

**Issue by CommissarTheHedgehog** [skyline-emu/skyline-games-list#909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1300

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/oppo_reno5_4g-10654.php

### Game Behaviour

Game won't start, crashes on start

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9288315/emulation.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a website name.
