### ISSUE TITLE
Grim Fandango Remastered

### ISSUE THREAD

**Issue by adamthepyramid** [skyline-emu/skyline-games-list#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1300

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

Ayn odin

### Game Behaviour

![Screenshot_20220810-092344](https://user-images.githubusercontent.com/105924769/183880516-055c4bde-7213-4dcc-a3a4-0cc6476c391c.png)
Gameplay and cut scenes are black 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9299229/emulation.zip)

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a piracy website.
