### ISSUE TITLE
Doom (2017)

### ISSUE THREAD

**Issue by Edrokski** [skyline-emu/skyline-games-list#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1308 

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_s20+_5g-10041.php

### Game Behaviour

Boots 
Gets threw all the Bethesda screens.
Crashes before any menu.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

![Screenshot_20220810-130135_Skyline](https://user-images.githubusercontent.com/58104117/184059907-9f79e75b-6c50-4e08-9654-e461dc6344d1.jpg)
![Screenshot_20220810-130146_Skyline](https://user-images.githubusercontent.com/58104117/184059983-0c5843c0-1ae4-455b-ad6c-32b04a75908e.jpg)

**Comment by Edrokski** [comment]
Sorry im a total noob is was trying to set labels do I do this or do the Skyline Devs

**Comment by mateoalfaro** [comment]
> Sorry im a total noob is was trying to set labels do I do this or do the Skyline Devs

The GitHub mods add the tags

**Comment by Crytonics** [comment]
Can you upload log of game tnx.

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.
