### ISSUE TITLE
Actraiser Renaissance

### ISSUE THREAD

**Issue by Edrokski** [skyline-emu/skyline-games-list#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1308

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_s20+_5g-10041.php

### Game Behaviour

Game Boots 
Goes past the loading screen and crashes green.

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

`
[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9305986/emulation.zip)
`

**Comment by Crytonics** [comment]
@Sovietfowl link in log

**Comment by Crytonics** [comment]
Closing because user is banned for piracy.

**Comment by Sovietfowl** [comment]
You are banned from the repository because your log contains a name of a piracy website.
