### ISSUE TITLE
Doki Doki Literature Club Plus

### ISSUE THREAD

**Issue by Destroy-God** [skyline-emu/skyline-games-list#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1308

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/realme_gt_5g-10689.php

### Game Behaviour

Just Crash

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9332615/emulation.zip)

**Comment by K11MCH1** [comment]
There is already an open issue for this game [here]https://github.com/skyline-emu/skyline-games-list/issues/356(url)
Please use the search tool before posting an issue.
