### ISSUE TITLE
Hollow Knight

### ISSUE THREAD

**Issue by guranu** [skyline-emu/skyline-games-list#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1058

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/oneplus_7-9623.php

### Game Behaviour

black screen
![Screenshot_20220430-025952](https://user-images.githubusercontent.com/103632948/166082078-4a1ff232-6413-43ae-973c-7c664a46e709.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/8595315/emulation.sklog.zip)

**Comment by davyson123** [comment]
Como faço para colocar o log no skyline?

**Comment by guranu** [comment]
huh why was this issue closed?

**Comment by Aztroloe** [comment]
Because the game is already reported.

**Comment by Mashhud2** [comment]
Как поиграть?
